### ISSUE TITLE
More optimal solutions for 7 cases 七个题有更优解法

### ISSUE THREAD

**Issue by instr3** [MathsFans/Tchisla#1]
1252#5 = 6
1257#5 = 7
1372#5 = 7
1794#7 = 7
1878#5 = 7
1883#5 = 8
1953#5 = 8
However, the formula of these solutions remains unknown, but exists.
这七个题的具体解法还不知道，但服务器上有正确解答的记录，因此解法应该存在。

**Comment by gaoyaoxin** [comment]
Thanks for your comments!
Now, have a look at these equations:
1257= 1252+5
1372 = 1252+5！
1883 = 1878+5
In this way, the key issue is to find the solutions to the following cases:
1252#5 = 6
1794#7 = 7
1878#5 = 7
1953#5 = 8

PS: I am eager to know where to find the exact number of digits used in the equation of the optimal solution.

**Comment by shaotq** [comment]
1252#5: (√√√√√5^5!+√√5/√5)*(√√5+√√5)

**Comment by shaotq** [comment]
1878#5: (√√√√√5^5!+√√5/√5)*(√√5+√√5+√√5)

**Comment by shaotq** [comment]
1953#5: ((√√√√5^5!/5-√5)*(√5+√5+√5)/5!

**Comment by shaotq** [comment]
1794#7: ((√√√7+√√√7)^7+√√√7/√√7)*(√√√7+√√√7)
All done, enjoy it!

**Comment by gaoyaoxin** [comment]
Phenomenal!

**Comment by shaotq** [comment]
My wechat ID: steve-sss,  I am interesting your job on Tchisla, hope we can discuss more!
